# Generated by Django 5.2.15 on 2026-07-05 10:05

import common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('google_sub', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'google identities',
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', '사용자'), ('ADVISOR', '조언가'), ('ADMIN', '관리자')], max_length=8)),
                ('action', models.CharField(choices=[('GRANT', '부여'), ('REVOKE', '회수')], max_length=8)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_role_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_role_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-acted_at'], name='rolegrant_user_acted_idx'), models.Index(fields=['-acted_at'], name='rolegrant_acted_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', '사용자'), ('ADVISOR', '조언가'), ('ADMIN', '관리자')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='accounts_userrole_user_role_unique')],
            },
        ),
    ]
