# Generated by Django 5.2.15 on 2026-07-07 11:08

import common.uuid7
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('concern_summary', models.CharField(max_length=100)),
                ('concern_type', models.CharField(choices=[('career_transition', '경력 전환'), ('job_change', '직종 전환'), ('burnout', '번아웃'), ('startup_failure', '사업 실패'), ('leadership', '리더십'), ('relationship', '관계'), ('life_direction', '인생 방향성(설계)'), ('major_life_decision', '인생의 중요한 의사결정'), ('education_choice', '학업 선택'), ('relocation', '이사'), ('finance_major_decision', '중요한 재무 의사결정')], max_length=40)),
                ('concern_type_secondary', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('career_transition', '경력 전환'), ('job_change', '직종 전환'), ('burnout', '번아웃'), ('startup_failure', '사업 실패'), ('leadership', '리더십'), ('relationship', '관계'), ('life_direction', '인생 방향성(설계)'), ('major_life_decision', '인생의 중요한 의사결정'), ('education_choice', '학업 선택'), ('relocation', '이사'), ('finance_major_decision', '중요한 재무 의사결정')], max_length=40), blank=True, default=list, size=2)),
                ('preferred_advisor_lane', models.CharField(choices=[('expert', '전문가'), ('senior', '인생 선배'), ('no_preference', '무관')], default='no_preference', max_length=16)),
                ('decision_context', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('display_alias', models.CharField(blank=True, default='', max_length=50)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('SUBMITTED', '제출됨'), ('ASSIGNED', '배정됨'), ('ANSWERED', '답변됨'), ('CLOSED', '종료됨')], default='SUBMITTED', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concerns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('triage_decision', models.CharField(choices=[('suitable', '적합'), ('needs_more_info', '추가 정보 필요'), ('out_of_scope', '범위 밖')], max_length=20)),
                ('match_rationale', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음')], default='normal', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_assignments', to=settings.AUTH_USER_MODEL)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='concerns.concern')),
            ],
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['author', 'deleted_at', '-created_at'], name='concern_author_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['status', '-created_at'], name='concern_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['concern_type', '-created_at'], name='concern_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['advisor', 'is_active'], name='assign_advisor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['concern', 'is_active'], name='assign_concern_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('concern', 'advisor'), name='assignment_concern_advisor_unique_active'),
        ),
    ]
