# Generated by Django 5.2.15 on 2026-07-07 11:10

import common.uuid7
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concerns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('directional_guidance', models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)])),
                ('reflective_questions', models.TextField(blank=True, default='')),
                ('considerations', models.TextField(blank=True, default='')),
                ('out_of_scope_flag', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', '접수'), ('REVIEWING', '심사중'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('DELETED', '삭제됨')], default='PENDING', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_advices', to=settings.AUTH_USER_MODEL)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advices', to='concerns.concern')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_advices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdviceHistory',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('directional_guidance', models.TextField()),
                ('reflective_questions', models.TextField()),
                ('considerations', models.TextField()),
                ('out_of_scope_flag', models.BooleanField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='advice.advice')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advice_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', '제출됨'), ('REVIEWED', '검토됨'), ('ARCHIVED', '보관됨')], default='SUBMITTED', max_length=10)),
                ('memo', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='advice.advice')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='advice',
            index=models.Index(fields=['advisor', '-created_at'], name='advice_advisor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='advice',
            index=models.Index(fields=['concern', 'status'], name='advice_concern_status_idx'),
        ),
        migrations.AddIndex(
            model_name='advice',
            index=models.Index(fields=['status', '-created_at'], name='advice_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='advice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'DELETED'), _negated=True), fields=('concern', 'advisor'), name='advice_concern_advisor_unique_active'),
        ),
        migrations.AddConstraint(
            model_name='advicehistory',
            constraint=models.UniqueConstraint(fields=('advice', 'version'), name='advicehistory_advice_version_unique'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', '-created_at'], name='feedback_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['author', '-created_at'], name='feedback_author_created_idx'),
        ),
    ]
