# Generated by Django 5.2.15 on 2026-07-07 11:06

import common.uuid7
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorApplication',
            fields=[
                ('id', models.UUIDField(default=common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('domain_category', models.CharField(choices=[('IT', 'IT'), ('경영', '경영'), ('인사', '인사'), ('금융', '금융'), ('의료', '의료'), ('교육', '교육'), ('기타', '기타')], max_length=20)),
                ('experience_band', models.CharField(choices=[('5-7', '5~7년'), ('8-12', '8~12년'), ('13+', '13년 이상')], max_length=8)),
                ('current_status', models.CharField(choices=[('재직', '재직'), ('프리랜서', '프리랜서'), ('휴직', '휴직'), ('휴식', '휴식'), ('은퇴', '은퇴')], max_length=10)),
                ('intended_lane', models.CharField(choices=[('expert', '전문가'), ('senior', '인생 선배')], max_length=8)),
                ('career_narrative', models.TextField()),
                ('advisable_concern_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('career_transition', '경력 전환'), ('job_change', '직종 전환'), ('burnout', '번아웃'), ('startup_failure', '사업 실패'), ('leadership', '리더십'), ('relationship', '관계'), ('life_direction', '인생 방향성(설계)'), ('major_life_decision', '인생의 중요한 의사결정'), ('education_choice', '학업 선택'), ('relocation', '이사'), ('finance_major_decision', '중요한 재무 의사결정')], max_length=40), default=list, size=None, validators=[django.core.validators.MinLengthValidator(1)])),
                ('sample_advice_response', models.TextField(validators=[django.core.validators.MinLengthValidator(200), django.core.validators.MaxLengthValidator(400)])),
                ('status', models.CharField(choices=[('PENDING', '접수'), ('REVIEWING', '심사중'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('WITHDRAWN', '철회')], default='PENDING', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_advisor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='advapp_status_sub_idx'), models.Index(fields=['applicant', '-submitted_at'], name='advapp_applicant_sub_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'REVIEWING', 'APPROVED'])), fields=('display_name',), name='advisor_app_display_name_unique_active')],
            },
        ),
    ]
