# Generated by Django 5.2.15 on 2026-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorapplication',
            name='domain_category',
            field=models.CharField(choices=[('기획·전략', '기획·전략'), ('인사·조직', '인사·조직'), ('마케팅·PR', '마케팅·PR'), ('재무·회계', '재무·회계'), ('IT·데이터', 'IT·데이터'), ('영업·무역', '영업·무역'), ('상품기획·MD', '상품기획·MD'), ('R&D', 'R&D'), ('의료', '의료'), ('교육', '교육'), ('기타', '기타')], max_length=20),
        ),
    ]
